apiVersion: v1
kind: Pod
metadata:
  name: urban-aura-curl
  labels:
    app: urban-aura-curl
spec:
  containers:
  - name: urban-aura-curl
    image: alpine
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"

