version: '1.0'

services:
  mongodb:
    image: mongo:7
    container_name: blogs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tarun
      MONGO_INITDB_DATABASE: blogDb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
