apiVersion: v1
kind: Service
metadata:
  name: urban-aura-svc
spec:
  selector:
    app: urban-aura
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: urban-aura-np-svc
spec:
  type: NodePort
  selector:
    app: urban-aura
  ports:
  - port: 80
    targetPort: 80


---

# apiVersion: v1
# kind: Service
# metadata:
#   name: urban-aura-lb-svc
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-enable-floating-ip: "false"
#     service.beta.kubernetes.io/azure-load-balancer-resource-group: urban-aura
# spec:
#   selector:
#     app: urban-aura
#   type: LoadBalancer
#   loadBalancerIP: 52.140.46.40
#   externalTrafficPolicy: Cluster
#   ports:
#   - port: 80
#     targetPort: 80
#     protocol: TCP

# minikube start -p netpol --cni calico