apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-db
  labels:
    app: mongodb
data:
  mongodb-init.js: |
    const dbName = process.env.DB_NAME;
    const dbUser = process.env.DB_USER;
    const dbPass = process.env.DB_PASS;

    db = db.getSiblingDB(dbName);

    console.log(`INITIALIZING DB: ${dbName}`);
    console.log(`CREATING User: ${dbUser}`);

    db.createUser({
      user: 'YWRtaW4K',
      pwd: 'dGFydW4K',
      roles: [
         {
            role: 'readWrite',
            db: 'devi'
         }
      ]
    });

    console.log(`INITIALIZING DB: ${dbName} Successfully`);

