apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-app
spec:
  selector:
    matchLabels:
      app: blob-app
  template:
    metadata:
      labels:
        app: blob-app
    spec:
      restartPolicy: Always
      containers:
      - name: blob-app
        image: tarunbhardwajdeveloper/blob-app:v0.0.2
        resources:
          requests:
            memory: "200Mi"
            cpu: "400m"
          limits:
            memory: "400Mi"
            cpu: "800m"
        ports:
        - containerPort: 80

# kubectl port-forward svc/blob-app-np 8080:80 -n prod
