apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-app-blog-service
spec:
  selector:
    matchLabels:
      app: blob-app-blog-service
  template:
    metadata:
      labels:
        app: blob-app-blog-service
    spec:
      containers:
      - name: blob-app-blog-service
        image: tarunbhardwajdeveloper/blob-app-blog-service:v0.0.2
        resources:
          requests:
            memory: "200Mi"
            cpu: "400m"
          limits:
            memory: "400Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
