apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - deploy-user-service.yml
  - deploy-blog-service.yml
  - deploy-event-bus.yml
  - services.yml
  - user-mongo.yml
  - blog-mongo.yml
  - app.deploy.yml