apiVersion: v1
kind: Service
metadata:
  name: blob-app-user-service
spec:
  selector:
    app: blob-app-user-service 
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blob-app-blog-service
spec:
  selector:
    app: blob-app-blog-service 
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blob-app-event-bus
spec:
  type: NodePort
  selector:
    app: blob-app-event-bus  
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blob-app
spec:
  selector:
    app: blob-app
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blob-app-np
spec:
  type: NodePort
  selector:
    app: blob-app
  ports:
  - port: 80
    targetPort: 80
