apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mongo
  template:
    metadata:
      labels:
        app: user-mongo
    spec:
      containers:
        - name: user-mongo
          image: mongo:7
          resources:
            requests:
              memory: "200Mi"
              cpu: "400m"
            limits:
              memory: "400Mi"
              cpu: "800m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_DATABASE
              value: "userDB"  
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: user-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongo-service
spec:
  type: ClusterIP
  selector:
    app: user-mongo
  ports:
    - port: 27017
      targetPort: 27017
