version: '1.0'

services:
  mongodb:
    image: mongo:7
    container_name: users-mongodb
    restart: unless-stopped
    ports:
      - "4001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tarun
      MONGO_INITDB_DATABASE: usersDb
    volumes:
      - mongo_data_users:/data/db

volumes:
  mongo_data_users:
