apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

namePrefix: dev-
nameSuffix: -alpha

commonLabels:
  team: development
  project: urban-aura
  tier: frontend
  env: dev

commonAnnotations:
  team: development
  maintainer: tarun

# images:
#   - name: nginx
#     newTag: '1.27.1'

replicas:
  - name: nginx
    count: 2

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config-map
    literals:
      - use_db=true
    options: 
      disableNameSuffixHash: true
  - name: db-init-config
    files:
      - other-key=init-db.js
 
secretGenerator:
  - name: env-secret
    envs:
      - .env.dev

patches:
  - path: update-resource.patch.yml
  - path: mount-db-init.patch.yml 

resources:
   - ../../base