apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1
        resources:
          requests:
            memory: "200i"
            cpu: "400m"
          limits:
            memory: "400Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
