apiVersion: v1
kind: Service
metadata:
  name: urban-aura-svc
  namespace: dev
  # annotations:
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: urban-aura
spec:
  selector:
    app: urban-aura
  type: LoadBalancer
  # loadBalancerIP: 20.51.187.128
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: urban-aura-np-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: urban-aura
  ports:
  - port: 80
    targetPort: 80


# 20.235.36.78

---

apiVersion: v1
kind: Service
metadata:
  name: urban-aura-lb
  namespace: dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: urban-aura
spec:
  type: LoadBalancer
  loadBalancerIP: 40.90.230.182
  selector:
    app: your-app
  ports:
  - port: 80
    targetPort: 80
