apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

# namePrefix: dev-
# nameSuffix: -alpha

# commonLabels:
#   team: production
#   project: urban-aura
#   tier: frontend
#   env: prod

commonAnnotations:
  team: production
  maintainer: tarun

replicas:
  - name: urban-aura
    count: 1

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: env-secret
    envs:
      - .env.prod

resources:
  - ../../base

patches:
  - path: patches/v1.0.2.patch.yml